ALTER TABLE public.freight_quote_requests
  ADD COLUMN IF NOT EXISTS reference_id         TEXT,
  ADD COLUMN IF NOT EXISTS language             TEXT DEFAULT 'en',
  ADD COLUMN IF NOT EXISTS transport_mode       TEXT,
  ADD COLUMN IF NOT EXISTS origin_country       TEXT,
  ADD COLUMN IF NOT EXISTS origin_city          TEXT,
  ADD COLUMN IF NOT EXISTS origin_terminal      TEXT,
  ADD COLUMN IF NOT EXISTS destination_country  TEXT,
  ADD COLUMN IF NOT EXISTS destination_city     TEXT,
  ADD COLUMN IF NOT EXISTS destination_terminal TEXT,
  ADD COLUMN IF NOT EXISTS commodity            TEXT,
  ADD COLUMN IF NOT EXISTS hs_code              TEXT,
  ADD COLUMN IF NOT EXISTS cargo_classification TEXT,
  ADD COLUMN IF NOT EXISTS quick_count          INTEGER,
  ADD COLUMN IF NOT EXISTS quick_weight         NUMERIC,
  ADD COLUMN IF NOT EXISTS packages             JSONB,
  ADD COLUMN IF NOT EXISTS un_number            TEXT,
  ADD COLUMN IF NOT EXISTS proper_shipping_name TEXT,
  ADD COLUMN IF NOT EXISTS hazard_class         TEXT,
  ADD COLUMN IF NOT EXISTS packing_group        TEXT,
  ADD COLUMN IF NOT EXISTS packaging_type       TEXT,
  ADD COLUMN IF NOT EXISTS transport_index      TEXT,
  ADD COLUMN IF NOT EXISTS isotope              TEXT,
  ADD COLUMN IF NOT EXISTS package_category     TEXT,
  ADD COLUMN IF NOT EXISTS document_paths       JSONB,
  ADD COLUMN IF NOT EXISTS comments             TEXT,
  ADD COLUMN IF NOT EXISTS status               TEXT DEFAULT 'new';
